// This file is auto-generated by scripts/generate.ts
import { ApiClient } from '@nexical/sdk-core';
import { OrchestratorModule } from '../../../apps/backend/modules/orchestrator-api/src/sdk/index.js';
import { UserModule } from '../../../apps/backend/modules/user-api/src/sdk/index.js';
export * as OrchestratorModuleTypes from '../../../apps/backend/modules/orchestrator-api/src/sdk/index.js';
export * as UserModuleTypes from '../../../apps/backend/modules/user-api/src/sdk/index.js';

export interface SdkRegistry {
  'orchestrator': OrchestratorModule;
  'user': UserModule;
}

export function initializeSdkRegistry(client: ApiClient): SdkRegistry {
  return {
    'orchestrator': new OrchestratorModule(client),
    'user': new UserModule(client),
  };
}
