import { globby } from 'globby';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
// Root is ../../.. from packages/sdk/scripts
const ROOT_DIR = path.resolve(__dirname, '../../..');

async function generate() {
    // Look for modules in apps/backend/modules
    const sdkFiles = await globby('apps/backend/modules/*/src/sdk/index.ts', { cwd: ROOT_DIR });

    const modules = sdkFiles.map((file) => {
        // file is like apps/backend/modules/user-api/src/sdk/index.ts
        const parts = file.split('/');
        // parts: ['apps', 'backend', 'modules', 'user-api', 'src', 'sdk', 'index.ts']
        const moduleName = parts[3]; // 'user-api'

        // Convention: user-api -> UserModule
        const effectiveName = moduleName.endsWith('-api')
            ? moduleName.replace(/-api$/, '')
            : moduleName;

        const className =
            effectiveName
                .split(/[-_]/)
                .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
                .join('') + 'Module';

        // Use relative path from packages/sdk/src/registry.generated.ts to apps/backend/modules/{name}/src/sdk/index.ts
        // packages/sdk/src -> ../../../apps/backend/modules/...
        const importPath = `../../../${file.replace('/index.ts', '')}/index.js`;

        // Strip "-api" suffix from property name if present
        const propertyName = moduleName.endsWith('-api') ? moduleName.replace(/-api$/, '') : moduleName;

        return { name: propertyName, className, importPath };
    });

    const imports = modules
        .map((m) => `import { ${m.className} } from '${m.importPath}';`)
        .join('\n');
    const exports = modules
        .map((m) => `export * as ${m.className}Types from '${m.importPath}';`)
        .join('\n');
    const properties = modules.map((m) => `  '${m.name}': ${m.className};`).join('\n');
    const initializers = modules
        .map((m) => `    '${m.name}': new ${m.className}(client),`)
        .join('\n');

    const content = `// This file is auto-generated by scripts/generate.ts
import { ApiClient } from '@nexical/sdk-core';
${imports}
${exports}

export interface SdkRegistry {
${properties}
}

export function initializeSdkRegistry(client: ApiClient): SdkRegistry {
  return {
${initializers}
  };
}
`;

    const outputPath = path.join(ROOT_DIR, 'packages/sdk/src/registry.generated.ts');
    await fs.writeFile(outputPath, content);
    console.info(`Generated SDK registry at ${outputPath}`);
}

generate().catch(console.error);
